import { AdminProject } from "@/types/admin";

export const MOCK_PROJECTS: AdminProject[] = [
  {
    id: "proj-1",
    title: "Enterprise Data Nexus",
    category: "Software",
    description: "A full-scale architectural overhaul of a global logistics platform, optimizing real-time tracking for 15M+ daily transactions.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2YxLvd3x5jPAxgZFL6XMO5u3FKnZOqm3Sw5jiYFwt6C_1rbby046caqliXpWGTpjLpPwnIvaeaOmdE4lDZVyZ_sdZvktvMtR48G9PDwq9PdT4z5dmEyDZmvTGdtk0tGLYG3aND_F-CKnXlxCnvDioVyszWJ-5hrLBoAQmefvVnmK51ys89hcKnm770jq6SVjM3Pg-onRL9YM_DO5PLioIGZ3Onw3JrHAYxnPC4ePN8pVa9SN1k4ErAvN0hneQVUTOK8JkgL9fql8e",
    status: "Published",
    featured: true,
    slug: "enterprise-data-nexus",
    createdDate: "2026-01-15",
    layoutSize: "featured",
  },
  {
    id: "proj-2",
    title: "FinStream Mobile",
    category: "Mobile",
    description: "Next-generation fintech application with biometrically secured transactions and AI-driven wealth management.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCuckOgEZiFaVbjMjtq4Zo95scq4OQnY3xbYO0vg55hHRFxf276lGegig9zB3AK0P9h1msdVHS3o2Hq4mfsI7JHByLnUh4JwsJn_a_SCkUErbsF5CMjrtPy44ySRZ6rUMH9TtUt6YHbksHOaDorq_O72YuI407w_8EDD-rV3m0Wxulxuc-8y1QE5YtkHY5Alaj5RTcQLJxbVg-hm2zCAX1FU1gcZeJqtPDBBIPpZjqhRUR3HS8St5n_qiKkEM2563tBOnZrGCewipVj",
    status: "Published",
    featured: false,
    slug: "finstream-mobile",
    createdDate: "2026-02-18",
    layoutSize: "side",
  },
  {
    id: "proj-3",
    title: "AeroSystem Portal",
    category: "UI/UX",
    description: "Intuitive interface design for aerospace maintenance systems, prioritizing safety and rapid cognitive processing.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBqZC_ts6xPw1yMzuro8TGLjnTBsZbb7MFoTe76yo3nJuQ9HBUZ0L8kJNtrd4w8wKM-AKF1-2tPSkn6UC5F6sQQ0QbKcrksnHzZnvuWGPAoSdwISOaMwLBjJhXeFbWD2VJEzKILYlmzkloDHl_7imdLKOyNq4MXrSqSZw7vFByIIjyl7lkHvc8EI9HZ7CCXIgSNVTS1EkkEo8UZmTXn4ka-eTZkg6Z0ctkE3PnFSZI25sEjKjuHkw5X_KlYC4XIGHVZjjbXFxOyWit-",
    status: "Published",
    featured: false,
    slug: "aerosystem-portal",
    createdDate: "2026-03-05",
    layoutSize: "standard",
  },
  {
    id: "proj-4",
    title: "CloudFlow Infrastructure",
    category: "Web",
    description: "Scalable microservices architecture for a SaaS leader, achieving 99.99% uptime with automated self-healing clusters.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAcyoGVDSOE8my2bXpNezqyX5xZj4XxnVACydbKHzVK6jhDKfhZl-nIOUQTe2wXx-vp9qN7DoVB7giBLDUZwZ3sK1UXWG97GedbH45VyphWgV2ewQlsC4r5CuKAIRO5F_thG9fY_EQXMlOuJZZWmyq0twPJc9RCCnbcYk9trPKLJcV1MbGEKpJ4WjdxsZUq84j-igQLDhSB6bg1HIWqqOuXZPLyPgm8lJbzW0g7Sf7xsg3yI2KMt-x77e3dkPMaAFpx7UuHvOQwayLo",
    status: "Published",
    featured: true,
    slug: "cloudflow-infrastructure",
    createdDate: "2026-03-20",
    layoutSize: "wide",
  },
  {
    id: "proj-5",
    title: "AutoCode Engine",
    category: "Software",
    description: "Proprietary automation framework that reduces legacy code migration time by 60% using neural pattern matching.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuApJEBBl9WPra88kicUUSc1g9dinI3-snijz_-kEac-L9Eh_49GRFug6fBAF-SRUAnbwWLTukPGyzl5NcEn_C4-MQ-5RxNHhRqFgJC69qoR707WV2E5iS2hwmlipH_36DdvD4iIeZ09KLezh753UW1tzXBzuSCYDuXRj1UblFpluQlwQx25QW4sEUiao8zYQECmp_4R-OLYX6hePCn7ZaN5PYAnPbGKnJPL44JSjrI5LAf0OT-64cBzGrQJIqx9SS4_IvPs1c5uWsTH",
    status: "Draft",
    featured: false,
    slug: "autocode-engine",
    createdDate: "2026-04-10",
    layoutSize: "standard",
  },
  {
    id: "proj-6",
    title: "OmniCommerce 360",
    category: "Web",
    description: "A headless commerce platform providing unified inventory across global physical and digital storefronts.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyRbRh4elt0iB_TbNluBJYEuMSXVyrc-wl6ebQjs2kw9I4KbGOUYgS8goVKLIfr6QglJSvT6fWAD3ls0im1fuGGZP5dIWd3Hc2fH5lQ-5TwHD3DdRnk6fmGAErcVWNZpkVxQ59BdpHCviHjj4xxm8iK1kK_NUNQ1FLrBX_KfVKClqxJMj2Usfq8BYM8aaBVdotaMUqH_S8XIO4vSjhcD5lI6Uzl8D03SiNeLIskR064eCS5mi5TwotTTXbWXD5Ecu9OZaNMQAY0OOm",
    status: "Published",
    featured: false,
    slug: "omnicommerce-360",
    createdDate: "2026-04-25",
    layoutSize: "standard",
  },
  {
    id: "proj-7",
    title: "Nexus CyberVault",
    category: "Software",
    description: "Military-grade cryptographic storage solution built using zero-knowledge proofs for enterprise cloud storage platforms.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuApJEBBl9WPra88kicUUSc1g9dinI3-snijz_-kEac-L9Eh_49GRFug6fBAF-SRUAnbwWLTukPGyzl5NcEn_C4-MQ-5RxNHhRqFgJC69qoR707WV2E5iS2hwmlipH_36DdvD4iIeZ09KLezh753UW1tzXBzuSCYDuXRj1UblFpluQlwQx25QW4sEUiao8zYQECmp_4R-OLYX6hePCn7ZaN5PYAnPbGKnJPL44JSjrI5LAf0OT-64cBzGrQJIqx9SS4_IvPs1c5uWsTH",
    status: "Draft",
    featured: false,
    slug: "nexus-cybervault",
    createdDate: "2026-05-02",
    layoutSize: "standard",
  },
  {
    id: "proj-8",
    title: "Quantum Ledger",
    category: "Software",
    description: "Quantum-resistant immutable transaction log for next-gen financial clearing houses.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB2YxLvd3x5jPAxgZFL6XMO5u3FKnZOqm3Sw5jiYFwt6C_1rbby046caqliXpWGTpjLpPwnIvaeaOmdE4lDZVyZ_sdZvktvMtR48G9PDwq9PdT4z5dmEyDZmvTGdtk0tGLYG3aND_F-CKnXlxCnvDioVyszWJ-5hrLBoAQmefvVnmK51ys89hcKnm770jq6SVjM3Pg-onRL9YM_DO5PLioIGZ3Onw3JrHAYxnPC4ePN8pVa9SN1k4ErAvN0hneQVUTOK8JkgL9fql8e",
    status: "Published",
    featured: true,
    slug: "quantum-ledger",
    createdDate: "2026-05-18",
    layoutSize: "featured",
  },
  {
    id: "proj-9",
    title: "PulseAnalytics Suite",
    category: "UI/UX",
    description: "A high-performance real-time telemetry dashboard designed for industrial monitoring in heavy manufacturing settings.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBqZC_ts6xPw1yMzuro8TGLjnTBsZbb7MFoTe76yo3nJuQ9HBUZ0L8kJNtrd4w8wKM-AKF1-2tPSkn6UC5F6sQQ0QbKcrksnHzZnvuWGPAoSdwISOaMwLBjJhXeFbWD2VJEzKILYlmzkloDHl_7imdLKOyNq4MXrSqSZw7vFByIIjyl7lkHvc8EI9HZ7CCXIgSNVTS1EkkEo8UZmTXn4ka-eTZkg6Z0ctkE3PnFSZI25sEjKjuHkw5X_KlYC4XIGHVZjjbXFxOyWit-",
    status: "Published",
    featured: false,
    slug: "pulseanalytics-suite",
    createdDate: "2026-05-24",
    layoutSize: "side",
  },
  {
    id: "proj-10",
    title: "Apex Logistics UI",
    category: "UI/UX",
    description: "Re-engineered terminal visual systems for port operators, reducing cargo processing latency by 32%.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBqZC_ts6xPw1yMzuro8TGLjnTBsZbb7MFoTe76yo3nJuQ9HBUZ0L8kJNtrd4w8wKM-AKF1-2tPSkn6UC5F6sQQ0QbKcrksnHzZnvuWGPAoSdwISOaMwLBjJhXeFbWD2VJEzKILYlmzkloDHl_7imdLKOyNq4MXrSqSZw7vFByIIjyl7lkHvc8EI9HZ7CCXIgSNVTS1EkkEo8UZmTXn4ka-eTZkg6Z0ctkE3PnFSZI25sEjKjuHkw5X_KlYC4XIGHVZjjbXFxOyWit-",
    status: "Published",
    featured: false,
    slug: "apex-logistics-ui",
    createdDate: "2026-06-01",
    layoutSize: "standard",
  },
  {
    id: "proj-11",
    title: "ScribeDoc AI",
    category: "Web",
    description: "Collaborative healthcare documenting software powered by secure, local voice transcription.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAcyoGVDSOE8my2bXpNezqyX5xZj4XxnVACydbKHzVK6jhDKfhZl-nIOUQTe2wXx-vp9qN7DoVB7giBLDUZwZ3sK1UXWG97GedbH45VyphWgV2ewQlsC4r5CuKAIRO5F_thG9fY_EQXMlOuJZZWmyq0twPJc9RCCnbcYk9trPKLJcV1MbGEKpJ4WjdxsZUq84j-igQLDhSB6bg1HIWqqOuXZPLyPgm8lJbzW0g7Sf7xsg3yI2KMt-x77e3dkPMaAFpx7UuHvOQwayLo",
    status: "Published",
    featured: false,
    slug: "scribedoc-ai",
    createdDate: "2026-06-08",
    layoutSize: "standard",
  },
  {
    id: "proj-12",
    title: "Helios Energy Grid",
    category: "Web",
    description: "Decentralized solar micro-grid management portal connecting private producers with micro-consumers.",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyRbRh4elt0iB_TbNluBJYEuMSXVyrc-wl6ebQjs2kw9I4KbGOUYgS8goVKLIfr6QglJSvT6fWAD3ls0im1fuGGZP5dIWd3Hc2fH5lQ-5TwHD3DdRnk6fmGAErcVWNZpkVxQ59BdpHCviHjj4xxm8iK1kK_NUNQ1FLrBX_KfVKClqxJMj2Usfq8BYM8aaBVdotaMUqH_S8XIO4vSjhcD5lI6Uzl8D03SiNeLIskR064eCS5mi5TwotTTXbWXD5Ecu9OZaNMQAY0OOm",
    status: "Published",
    featured: false,
    slug: "helios-energy-grid",
    createdDate: "2026-06-12",
    layoutSize: "standard",
  }
];
