import { AdminTestimonial } from "@/types/admin";

export const MOCK_TESTIMONIALS: AdminTestimonial[] = [
  {
    id: "test-1",
    clientName: "Sarah Jenkins",
    position: "VP of Engineering",
    company: "LogiRoute Global",
    rating: 5,
    content: "HexaKode's re-architecture of our logistics tracking system was flawless. We saw a 40% reduction in database CPU utilization on day one.",
    status: "Active",
    date: "2026-02-10",
  },
  {
    id: "test-2",
    clientName: "Marcus Vance",
    position: "Chief Product Officer",
    company: "FinStream Inc.",
    rating: 5,
    content: "The mobile app designed by HexaKode has set a new standard for biometric security in our space. Exceptional engineering discipline.",
    status: "Active",
    date: "2026-03-01",
  },
  {
    id: "test-3",
    clientName: "Elena Rostova",
    position: "Head of Operations",
    company: "AeroSystems",
    rating: 4,
    content: "Excellent collaboration on the maintenance terminal UI. The cognitive load reduction was immediately validated by our field operators.",
    status: "Active",
    date: "2026-03-12",
  },
  {
    id: "test-4",
    clientName: "David Chen",
    position: "Founder & CEO",
    company: "CloudFlow",
    rating: 5,
    content: "Our uptime metrics have never looked better. The self-healing clustering code HexaKode delivered is bulletproof.",
    status: "Active",
    date: "2026-04-05",
  },
  {
    id: "test-5",
    clientName: "Amanda Geller",
    position: "Director of IT",
    company: "OmniCommerce",
    rating: 5,
    content: "Unified our multi-channel inventory into a headless schema that actually works. A masterclass in software architecture.",
    status: "Active",
    date: "2026-05-01",
  },
  {
    id: "test-6",
    clientName: "John Doe",
    position: "Security Lead",
    company: "CyberVault",
    rating: 4,
    content: "Implementation of zero-knowledge proofs is robust and meets all compliance regulations. Highly recommended team.",
    status: "Pending",
    date: "2026-05-15",
  },
  {
    id: "test-7",
    clientName: "Robert Kovac",
    position: "Principal Architect",
    company: "Quantum Clearings",
    rating: 5,
    content: "HexaKode demonstrated an outstanding level of technical expertise in delivering our quantum-resistant ledger prototype.",
    status: "Active",
    date: "2026-06-02",
  },
  {
    id: "test-8",
    clientName: "Leah Goldberg",
    position: "Director of Product",
    company: "ScribeDoc Health",
    rating: 4,
    content: "The voice transcription features operate reliably in low-network conditions, keeping our doctors focused on patient care.",
    status: "Pending",
    date: "2026-06-11",
  }
];
